CHAIN_ID = 17000

[LIDO_CONTRACTS]
ST_ETH = "0x5c7b199956b976bb472a0aa2facc5ded425a1313"
WST_ETH = "0x27c11a81b16526664d28a4222b0ee31704405b75"
WITHDRAWAL_QUEUE = "0x2e22f14c5829bd021911820f7408ad3b71a6584b"


[EMERGENCY_PROTECTED_TIMELOCK_CONFIG]
MIN_EXECUTION_DELAY = 300
AFTER_SUBMIT_DELAY = 900
MAX_AFTER_SUBMIT_DELAY = 1800
AFTER_SCHEDULE_DELAY = 900
MAX_AFTER_SCHEDULE_DELAY = 1800
EMERGENCY_MODE_DURATION = 900
MAX_EMERGENCY_MODE_DURATION = 1800
EMERGENCY_PROTECTION_DURATION = 900
MAX_EMERGENCY_PROTECTION_DURATION = 1800

# Temporary Governance
EMERGENCY_GOVERNANCE_PROPOSER = "0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"

#
TEMPORARY_EMERGENCY_GOVERNANCE_PROPOSER = "0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"

EMERGENCY_ACTIVATION_COMMITTEE = "0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"
EMERGENCY_EXECUTION_COMMITTEE = "0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"

[DUAL_GOVERNANCE_CONFIG]
ADMIN_PROPOESER = "0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"
RESEAL_COMMITTEE = "0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"
PROPOSALS_CANCELLER = "0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"
MIN_WITHDRAWALS_BATCH_SIZE = 1
MAX_SEALABLE_WITHDRAWAL_BLOCKERS_COUNT = 255
FIRST_SEAL_RAGE_QUIT_SUPPORT = 300
SECOND_SEAL_RAGE_QUIT_SUPPORT = 1500
MIN_ASSETS_LOCK_DURATION = 300
MAX_MIN_ASSETS_LOCK_DURATION = 3600
VETO_SIGNALLING_MIN_DURATION = 300
VETO_SIGNALLING_MIN_ACTIVE_DURATION = 300
VETO_SIGNALLING_MAX_DURATION = 1800
VETO_SIGNALLING_DEACTIVATION_MAX_DURATION = 1800
VETO_COOLDOWN_DURATION = 900
RAGE_QUIT_EXTENSION_PERIOD_DURATION = 900
RAGE_QUIT_ETH_WITHDRAWALS_MIN_DELAY = 300
RAGE_QUIT_ETH_WITHDRAWALS_MAX_DELAY = 1800
RAGE_QUIT_ETH_WITHDRAWALS_DELAY_GROWTH = 1296000

[TIEBREAKER_CONFIG]
QUORUM = 1
EXECUTION_DELAY = 900
MIN_ACTIVATION_TIMEOUT = 300
ACTIVATION_TIMEOUT = 900
MAX_ACTIVATION_TIMEOUT = 1800
SEALABLE_WITHDRAWAL_BLOCKERS = ["0x2e22f14c5829bd021911820f7408ad3b71a6584b"]

[[TIEBREAKER_CONFIG.COMMITTEES]] # Influencers
QUORUM = 1
MEMBERS = ["0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"]

[[TIEBREAKER_CONFIG.COMMITTEES]] # Node Operators
QUORUM = 1
MEMBERS = ["0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"]

[[TIEBREAKER_CONFIG.COMMITTEES]] # Protocols
QUORUM = 1
MEMBERS = ["0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"]
