chain_id = 17000

# ======================
# DUAL GOVERNANCE CONFIG
# ======================

[dual_governance]
admin_proposer = "0xdA7d2573Df555002503F29aA4003e398d28cc00f"                 # DAO Voting
proposals_canceller = "0xdA7d2573Df555002503F29aA4003e398d28cc00f"            # DAO Voting
reseal_committee = "0x17A283c01dCc0F1d3D67b24E341e142DF78807D4"               # Gnosis Multisig
sealable_withdrawal_blockers = ["0xC455F41f0A5a01359B6044b762A85B90324Ea5F0"] # Mock Withdrawal queue
tiebreaker_activation_timeout = 900

[dual_governance.signalling_tokens]
st_eth = "0xea403E925EA33DFB268047bFf224f1b1D4Fa3883"           # Mock stETH
withdrawal_queue = "0xC455F41f0A5a01359B6044b762A85B90324Ea5F0" # Mock Withdrawal queue
wst_eth = "0x32A81f4aA79b20239350F8Fd28d20Ad85FD2ecdD"          # Mock wstETH

[dual_governance.sanity_check_params]
max_min_assets_lock_duration = 3600
max_sealable_withdrawal_blockers_count = 255
max_tiebreaker_activation_timeout = 1800
min_tiebreaker_activation_timeout = 300
min_withdrawals_batch_size = 1

[dual_governance_config_provider]
first_seal_rage_quit_support = 300
min_assets_lock_duration = 300
rage_quit_eth_withdrawals_delay_growth = 1296000
rage_quit_eth_withdrawals_max_delay = 1800
rage_quit_eth_withdrawals_min_delay = 300
rage_quit_extension_period_duration = 900
second_seal_rage_quit_support = 1500
veto_cooldown_duration = 900
veto_signalling_deactivation_max_duration = 1800
veto_signalling_max_duration = 1800
veto_signalling_min_active_duration = 300
veto_signalling_min_duration = 300

# ======================
# EMERGENCY PROTECTED TIMELOCK CONFIG
# ======================

[timelock]
after_schedule_delay = 120
after_submit_delay = 120

[timelock.sanity_check_params]
max_after_schedule_delay = 1800
max_after_submit_delay = 1800
max_emergency_mode_duration = 86400          # 1 day
max_emergency_protection_duration = 31536000 # 1 year
min_execution_delay = 120

[timelock.emergency_protection]
emergency_activation_committee = "0x8dA88a400500955E17FaB806DE606B025D033C66" # Gnosis Multisig
emergency_execution_committee = "0x7bAd309E8f1501C71f33dBbc843a462dAbF6Eb22"  # Gnosis Multisig
emergency_governance_proposer = "0x17A283c01dCc0F1d3D67b24E341e142DF78807D4"  # Gnosis Multisig
emergency_mode_duration = 86400                                               # 1 day
emergency_protection_end_date = 1767225600                                    # Thu Jan 01 2026 00:00:00 GMT+0000

# ======================
# TIEBREAKER CONFIG
# ======================

[tiebreaker]
committees_count = 3
execution_delay = 900
quorum = 1

[[tiebreaker.committees]] # Influencers (participants from Devnet dry run multisig)
members = [
    "0x14df797E7910D320931016E87133D0977eCa3c54",
    "0x6FD09F5b4341C79CBDf679bccC2394C6FD7D0016",
    "0xe8B2097674daF8fC3DcCDDf05a2cBeF8253A4bAB",
    "0x7Cd64b87251f793027590c34b206145c3aa362Ae",
    "0x526d46eCa1d7969924e981ecDbcAa74e9f0EE566",
    "0x6389CBcF38172a1e8eCF1C34c00cd7f603AfB80C",
]
quorum = 1

[[tiebreaker.committees]] # Node Operators (participants from Devnet dry run multisig)
members = [
    "0x14df797E7910D320931016E87133D0977eCa3c54",
    "0x6FD09F5b4341C79CBDf679bccC2394C6FD7D0016",
    "0xe8B2097674daF8fC3DcCDDf05a2cBeF8253A4bAB",
    "0x7Cd64b87251f793027590c34b206145c3aa362Ae",
    "0x526d46eCa1d7969924e981ecDbcAa74e9f0EE566",
    "0x6389CBcF38172a1e8eCF1C34c00cd7f603AfB80C",
]
quorum = 1

[[tiebreaker.committees]] # Protocols (participants from Devnet dry run multisig)
members = [
    "0x14df797E7910D320931016E87133D0977eCa3c54",
    "0x6FD09F5b4341C79CBDf679bccC2394C6FD7D0016",
    "0xe8B2097674daF8fC3DcCDDf05a2cBeF8253A4bAB",
    "0x7Cd64b87251f793027590c34b206145c3aa362Ae",
    "0x526d46eCa1d7969924e981ecDbcAa74e9f0EE566",
    "0x6389CBcF38172a1e8eCF1C34c00cd7f603AfB80C",
]
quorum = 1
