chain_id = 17000

# ======================
# DUAL GOVERNANCE CONFIG
# ======================

[dual_governance]
admin_proposer = "0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"
reseal_committee = "0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"
proposals_canceller = "0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"
tiebreaker_activation_timeout = 900
sealable_withdrawal_blockers = ["0x2e22f14c5829bd021911820f7408ad3b71a6584b"]

[dual_governance.signalling_tokens]
st_eth = "0x5c7b199956b976bb472a0aa2facc5ded425a1313"
wst_eth = "0x27c11a81b16526664d28a4222b0ee31704405b75"
withdrawal_queue = "0x2e22f14c5829bd021911820f7408ad3b71a6584b"

[dual_governance.sanity_check_params]
min_withdrawals_batch_size = 1
max_tiebreaker_activation_timeout = 1800
min_tiebreaker_activation_timeout = 300
max_sealable_withdrawal_blockers_count = 255
max_min_assets_lock_duration = 3600

[dual_governance_config_provider]
first_seal_rage_quit_support = 300
second_seal_rage_quit_support = 1500
min_assets_lock_duration = 300
veto_signalling_min_duration = 300
veto_signalling_min_active_duration = 300
veto_signalling_max_duration = 1800
veto_signalling_deactivation_max_duration = 1800
veto_cooldown_duration = 900
rage_quit_extension_period_duration = 900
rage_quit_eth_withdrawals_min_delay = 300
rage_quit_eth_withdrawals_max_delay = 1800
rage_quit_eth_withdrawals_delay_growth = 1296000

# ======================
# EMERGENCY PROTECTED TIMELOCK CONFIG
# ======================

[timelock]
after_submit_delay = 900
after_schedule_delay = 900

[timelock.sanity_check_params]
min_execution_delay = 300
max_after_submit_delay = 1800
max_after_schedule_delay = 1800
max_emergency_mode_duration = 86400          # 1 day
max_emergency_protection_duration = 31536000 # 1 year

[timelock.emergency_protection]
emergency_mode_duration = 86400                                               # 1 day
# The following value for is dangerous. I propose to change it to 1765200000 - Mon, 08 Dec 2025 13:20:00 GMT
emergency_protection_end_date = 1767225600                                    # Thu Jan 01 2026 00:00:00 GMT+0000
emergency_governance_proposer = "0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"
emergency_activation_committee = "0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"
emergency_execution_committee = "0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"

# ======================
# TIEBREAKER CONFIG
# ======================

[tiebreaker]
quorum = 1
committees_count = 3
execution_delay = 900

[[tiebreaker.committees]] # Influencers
quorum = 1
members = ["0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"]

[[tiebreaker.committees]] # Node Operators
quorum = 1
members = ["0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"]

[[tiebreaker.committees]] # Protocols
quorum = 1
members = ["0x526d46eca1d7969924e981ecdbcaa74e9f0ee566"]
