name: Slither Analysis

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    env:
      FORGE_VERSION: 'v1.0.0'
      PYTHON_VERSION: '3.10'

    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - name: Install Python dependencies with Poetry
        run: poetry install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ env.FORGE_VERSION }}

      - name: Run Slither
        continue-on-error: true
        run: |
          poetry run slither . --sarif results.sarif

      - name: Check results.sarif presence
        id: sarif_check
        run: |
          if [ -s results.sarif ]; then
            echo "present=true" >> $GITHUB_OUTPUT
          else
            echo "present=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload SARIF file
        if: steps.sarif_check.outputs.present == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
